import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";

interface FlyerDocumentProps {
  businessName: string;
  address: string;
  phone: string;
  qrCodeDataUrl: string;
  publicUrl: string;
}

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 40,
    alignItems: "center",
  },
  header: {
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#1a1a1a",
  },
  subheader: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 30,
    color: "#4a4a4a",
  },
  qrContainer: {
    alignItems: "center",
    marginVertical: 30,
    padding: 20,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    borderRadius: 10,
  },
  qrCode: {
    width: 250,
    height: 250,
  },
  qrLabel: {
    fontSize: 14,
    marginTop: 15,
    textAlign: "center",
    color: "#666",
  },
  infoSection: {
    marginTop: 30,
    width: "100%",
    paddingHorizontal: 20,
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "center",
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "bold",
    marginRight: 10,
    color: "#1a1a1a",
  },
  infoValue: {
    fontSize: 14,
    color: "#4a4a4a",
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#999",
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 20,
  },
});

export function FlyerDocument({
  businessName,
  address,
  phone,
  qrCodeDataUrl,
  publicUrl,
}: FlyerDocumentProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.header}>{businessName}</Text>
        <Text style={styles.subheader}>Scan to view our menu & hours</Text>

        <View style={styles.qrContainer}>
          <Image src={qrCodeDataUrl} style={styles.qrCode} />
          <Text style={styles.qrLabel}>Scan with your phone camera</Text>
        </View>

        <View style={styles.divider} />

        <View style={styles.infoSection}>
          {address && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>📍 Address:</Text>
              <Text style={styles.infoValue}>{address}</Text>
            </View>
          )}
          {phone && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>📞 Phone:</Text>
              <Text style={styles.infoValue}>{phone}</Text>
            </View>
          )}
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>🌐 Website:</Text>
            <Text style={styles.infoValue}>{publicUrl}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by Diner SaaS • Print this flyer for your tables!
        </Text>
      </Page>
    </Document>
  );
}
